# Generated by Django 5.1.4 on 2026-03-31 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='buildings.building')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('meter_id', models.CharField(max_length=50, unique=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.tower')),
            ],
            options={
                'ordering': ['floor', 'number'],
                'unique_together': {('tower', 'number')},
            },
        ),
    ]
