# Generated by Django 5.1.4 on 2026-03-31 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='m³', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='measurements/%Y/%m/')),
                ('status', models.CharField(choices=[('verified', 'Validado'), ('pending_review', 'Pendiente'), ('rejected', 'Rechazado')], default='pending_review', max_length=20)),
                ('meter_type', models.CharField(choices=[('analog', 'Analógico'), ('digital_drum', 'Digital Tambor'), ('digital', 'Digital')], default='analog', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='buildings.apartment')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
